<?php 

if (function_exists('acf_add_options_page')) {
  $parent = acf_add_options_page(array(
    'page_title' => 'Configuracion',
    'menu_title' => 'General',
    'menu_slug' => 'general',
    'capability' => 'edit_posts',
    'position' => false,
    'icon_url' => false,
    'redirect' => false
  ));
}

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_5a1563040264f',
	'title' => 'General',
	'fields' => array (
		array (
			'key' => 'field_5a15633ef86f8',
			'label' => 'Header',
			'name' => 'header',
			'type' => 'group',
			'instructions' => 'Aquí podrá agregar los datos necesarios para la cabecera de su sitio web.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array (
				array (
					'ID' => 177,
					'key' => 'field_5a15647d9bf5b',
					'label' => 'Logo',
					'name' => 'logo',
					'prefix' => 'acf',
					'type' => 'image',
					'value' => NULL,
					'menu_order' => 0,
					'instructions' => '',
					'required' => 0,
					'id' => '',
					'class' => '',
					'conditional_logic' => 0,
					'parent' => 170,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'_name' => 'logo',
					'_prepare' => 0,
					'_valid' => 1,
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'ID' => 178,
					'key' => 'field_5a1564979bf5c',
					'label' => 'Color de fondo',
					'name' => 'color',
					'prefix' => 'acf',
					'type' => 'color_picker',
					'value' => NULL,
					'menu_order' => 1,
					'instructions' => '',
					'required' => 0,
					'id' => '',
					'class' => '',
					'conditional_logic' => 0,
					'parent' => 170,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'_name' => 'color',
					'_prepare' => 0,
					'_valid' => 1,
					'default_value' => '#009AFA',
				),
			),
		),
		array (
			'key' => 'field_5a156947b2f99',
			'label' => 'Footer',
			'name' => 'footer',
			'type' => 'group',
			'instructions' => 'Aquí podrá agregar los datos necesarios para el pie de página de su sitio web.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array (
				array (
					'ID' => 181,
					'key' => 'field_5a156947b2f9a',
					'label' => 'Logo',
					'name' => 'logo',
					'prefix' => 'acf',
					'type' => 'image',
					'value' => NULL,
					'menu_order' => 0,
					'instructions' => '',
					'required' => 0,
					'id' => '',
					'class' => '',
					'conditional_logic' => 0,
					'parent' => 180,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'_name' => 'logo',
					'_prepare' => 0,
					'_valid' => 1,
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'ID' => 182,
					'key' => 'field_5a156947b2f9b',
					'label' => 'Color de fondo',
					'name' => 'color',
					'prefix' => 'acf',
					'type' => 'color_picker',
					'value' => NULL,
					'menu_order' => 1,
					'instructions' => '',
					'required' => 0,
					'id' => '',
					'class' => '',
					'conditional_logic' => 0,
					'parent' => 180,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'_name' => 'color',
					'_prepare' => 0,
					'_valid' => 1,
					'default_value' => '#009AFA',
				),
			),
		),
		array (
			'key' => 'field_5a156356f86f9',
			'label' => 'Facebook',
			'name' => 'facebook',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5a15637ef86fa',
			'label' => 'Google Plus',
			'name' => 'google_plus',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5a156392f86fb',
			'label' => 'Instagram',
			'name' => 'instagram',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5a15639df86fc',
			'label' => 'Twitter',
			'name' => 'twitter',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_5a1563acf86fd',
			'label' => 'Youtube',
			'name' => 'youtube',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'general',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

?>